[tox]
envlist = py313
isolated_build = false
skip_missing_interpreters = true

[testenv]
setenv =
    PYTHONPATH = {toxinidir}
deps = -rrequirements.txt
commands =
    python -m unittest discover -s five9/tests -p 'test*.py'
